---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.homebrew
  - name: geerlingguy.mas

collections:
  - name: community.general
    version: ">=3.0.0"
  - name: geerlingguy.mac
    version: ">=3.0.0"
