---
- name: Check if chezmoi is installed
  ansible.builtin.stat:
    path: "~/.local/share/chezmoi"
  register: chezmoi_dir

- name: Install chezmoi
  ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply {{ GITHUB_USERNAME }}
  when: not chezmoi_dir.stat.exists

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0700'
  loop:
    - { path: "{{ ansible_env.HOME }}/bin/pwsh" }
    - { path: "{{ ansible_env.HOME }}/.config/omp_themes" }

- name: Download OMP themes
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.HOME }}/.config/omp_themes/{{ item.dest }}"
    mode: '0644'
  loop:
    - { url: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/kali.omp.json", dest: "kali.omp.json" }
    - { url: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/microverse-power.omp.json", dest: "microverse-power.omp.json" }