---
- name: Check if chezmoi is installed
  ansible.builtin.stat:
    path: "~/.local/share/chezmoi"
  register: chezmoi_dir

- name: Install chezmoi
  ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply {{ GITHUB_USERNAME }}
  when: not chezmoi_dir.stat.exists

- name: Create home bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'

- name: Create pwsh script dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin/pwsh"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'

- name: Create OMP themes folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/omp_themes"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'

- name: Download ZSH OMP theme
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/kali.omp.json"
    dest: "{{ ansible_env.HOME }}/.config/omp_themes"
    mode: '0644'

- name: Download PWSH OMP theme
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/microverse-power.omp.json"
    dest: "{{ ansible_env.HOME }}/.config/omp_themes"
    mode: '0644'
