---
- name: Add Flathub repository
  ansible.builtin.command:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ linux_flatpak_packages }}"
  become: true
