---
- name: Set default AppleKeyPress in VSCode to support vim extension
  community.general.osx_defaults:
    domain: com.microsoft.VSCode
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present

- name: Set Dock to auto-hide
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

- name: Set Dock icon size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 48
    state: present

- name: Restart Dock to apply changes
  ansible.builtin.command: killall Dock
  changed_when: false
