---
- name: Install Chocolatey package manager
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present

- name: Install packages using Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name:
      - package1
      - package2
      - package3
    state: present

- name: Installs sshd service
  ansible.windows.win_feature:
    name: OpenSSH.Server
    state: present

- name: Sets sshd service to start automatically
  ansible.windows.win_service:
    name: sshd
    start_mode: auto
    state: started
