---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    configure_dotfiles: false
    configure_linux: true
    configure_macos: false
    configure_mas: false
    configure_dock: false
    github_username: "test-user"

  pre_tasks:
    - name: Set OS facts
      ansible.builtin.set_fact:
        is_macos: "{{ ansible_system == 'Darwin' }}"
        is_fedora: "{{ ansible_distribution == 'Fedora' }}"
        is_debian: "{{ ansible_os_family == 'Debian' }}"
        is_linux: "{{ ansible_system == 'Linux' }}"

  roles:
    - role: system
