---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: fedora-39
    image: quay.io/ansible/molecule-fedora:39
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    group_vars:
      all:
        configure_dotfiles: false
        configure_linux: true
        configure_macos: false
        configure_mas: false
        configure_dock: false
        github_username: "test-user"
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
