---
# Prepare step for Molecule tests
- name: Prepare test environment
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Fix Fedora libdnf5 issues
      ansible.builtin.dnf:
        name:
          - python3-libdnf5
          - python3-dnf
        state: present
      when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'
      ignore_errors: true

    - name: Update package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install basic packages for testing
      ansible.builtin.package:
        name:
          - curl
          - git
          - python3
        state: present
      ignore_errors: true
