---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Check zsh is installed
      ansible.builtin.command: zsh --version
      register: zsh_version
      changed_when: false
      failed_when: zsh_version.rc != 0

    - name: Check root default shell is zsh
      ansible.builtin.command: getent passwd root
      register: root_passwd
      changed_when: false

    - name: Assert root shell is zsh
      ansible.builtin.assert:
        that: "'/zsh' in root_passwd.stdout"
        fail_msg: "Default shell for root is not zsh"
